version: '3.8'

networks:
  app-network:

services:
  db:
    image: postgres:14-alpine
    container_name: abcall_db
    networks:
      - app-network
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abcall_db
    ports:
        - "5442:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./microservices/auth
      dockerfile: Dockerfile
    container_name: auth_abcall
    networks:
      - app-network
    env_file:
        - "microservices/auth/.env"
    ports:
      - "3000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth:8000/health"]

  user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    container_name: user_abcall
    networks:
      - app-network
    env_file:
        - "microservices/user/.env"
    ports:
      - "3001:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user:8000/health"]
