###################################
# INGRESS
###################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  labels:
    name: gateway-ingress
  annotations:
    kube.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /auth
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - pathType: Prefix
        path: /user
        backend:
          service:
            name: user-service
            port:
              number: 80
      - pathType: Prefix
        path: /company
        backend:
          service:
            name: user-service
            port:
              number: 80
      - pathType: Prefix
        path: /issues_management
        backend:
            service:
                name: issues-management-service
                port:
                  number: 80
