name: Build and Test microservices

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

        # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
            compose-file: "docker-compose.yaml"
            test-container: "auth"
            test-command: "pytest --cov-report term --cov=src tests/ -c pytest.ini --cov-fail-under=80"
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
            compose-file: "docker-compose.yaml"
            test-container: "user"
            test-command: "pytest --cov-report term --cov=src tests/ -c pytest.ini --cov-fail-under=80"
