name: Build and test

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt;
    - name: Test with pytest
      run: |
        pytest
    - name: Upload build data
      uses: actions/upload-artifact@v3
      with:
        name: builded_data
        path: .
